apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "spur.fullname" . }}
  namespace: {{ include "spur.fullname" . }}
  labels:
  {{- include "spur.labels" . | nindent 4 }}
data:
  {{ .Values.appSettingsPath | base }}: |
    {
      "Serilog": {
        "MinimumLevel": {
          "Default": {{ .Values.logLevel | quote }},
        }
      },
      "FeatureManagement":
      {{- .Values.featureManagement | mustToPrettyJson | indent 6 }}
    }
