apiVersion: batch/v1
kind: CronJob
metadata:
  name: {{ include "tevling.fullname" . }}
  namespace: {{ include "tevling.fullname" . }}
  labels:
  {{- include "tevling.labels" . | nindent 4 }}
spec:
  schedule: "0 3 * * *"
  concurrencyPolicy: Forbid
  successfulJobsHistoryLimit: 3
  failedJobsHistoryLimit: 1
  jobTemplate:
    spec:
      backoffLimit: 3
      template:
        spec:
          containers:
          - name: tevling
            image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
            imagePullPolicy: Always
            args: ['import', '1']
            env:
            - name: TEVLING_APPSETTINGS
              value: {{ .Values.appSettingsPath }}
            envFrom:
            - secretRef:
                name: {{ include "tevling.fullname" . }}
            securityContext:
            {{- .Values.securityContext | toYaml | nindent 14 }}
            resources:
            {{- .Values.resources | toYaml | nindent 14 }}
            volumeMounts:
            - mountPath: {{ .Values.appSettingsPath | dir }}
              name: config
          restartPolicy: OnFailure
          securityContext:
          {{- .Values.podSecurity | toYaml | nindent 12 }}
          volumes:
          - name: config
            configMap:
              name: {{ include "tevling.fullname" . }}
