apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "tevling.fullname" . }}
  namespace: {{ include "tevling.fullname" . }}
  labels:
  {{- include "tevling.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicas }}
  revisionHistoryLimit: {{ .Values.revisionHistoryLimit }}
  selector:
    matchLabels:
    {{- include "tevling.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
      {{- include "tevling.selectorLabels" . | nindent 8 }}
    spec:
      containers:
      - env:
        - name: ASPNETCORE_HTTP_PORTS
          value: {{- $containerPort := 8080 }} {{ quote $containerPort }}
        - name: TEVLING_APPSETTINGS
          value: {{ .Values.appSettingsPath }}
        envFrom:
        - secretRef:
            name: {{ include "tevling.fullname" . }}
        image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
        name: tevling
        securityContext:
        {{- .Values.securityContext | toYaml | nindent 10 }}
        ports:
        - containerPort: {{ $containerPort }}
          name: http
        livenessProbe:
          httpGet:
            path: /healthz
            port: http
        resources:
        {{- .Values.resources | toYaml | nindent 10 }}
        volumeMounts:
        - mountPath: /app/storage
          name: data
        - mountPath: {{ .Values.appSettingsPath | dir }}
          name: config
      securityContext:
      {{- .Values.podSecurity | toYaml | nindent 8 }}
      volumes:
      - name: data
        persistentVolumeClaim:
          claimName: {{ include "tevling.fullname" . }}-pvc
      - name: config
        configMap:
          name: {{ include "tevling.fullname" . }}
