apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "spur.fullname" . }}-pvc
  namespace: {{ include "spur.fullname" . }}
  labels:
  {{- include "spur.labels" . | nindent 4 }}
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.pvc.storageRequest }}
