apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: tevling
  namespace: argocd
  annotations:
    argocd-image-updater.argoproj.io/image-list: tevling=ghcr.io/veloek/tevling:latest
    argocd-image-updater.argoproj.io/tevling.update-strategy: digest
spec:
  project: default
  source:
    repoURL: https://github.com/veloek/tevling.git
    targetRevision: HEAD
    path: helm
    helm:
      parameters:
      - name: image.tag
        value: latest
  destination:
    server: https://kubernetes.default.svc
    namespace: tevling
  ignoreDifferences:
  - kind: Secret
    name: tevling
    jsonPointers:
    - /data
  - kind: ConfigMap
    name: tevling
    jsonPointers:
    - /data
  syncPolicy:
    automated: {}
    syncOptions:
    - RespectIgnoreDifferences=true
