name: Docker Image CI

on:
  push:
    branches: [ "main" ]

env:
  DOCKER_REPO: ${{ secrets.DOCKER_REPO }}
  DOCKER_TOKEN: ${{ secrets.DOCKER_TOKEN }}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Docker login
      run: docker login -u $DOCKER_REPO -p $DOCKER_TOKEN

    - name: Docker buildx setup
      run: docker buildx create --use --bootstrap

    - name: Docker build and push
      run: docker buildx build . --push --file Dockerfile --tag $DOCKER_REPO/spur:$GITHUB_SHA --tag $DOCKER_REPO/spur:latest --platform linux/arm64,linux/arm,linux/amd64
