name: Docker Image CI

on:
  workflow_dispatch: {}
  push:
    branches: [ "main" ]
    paths: [ "Tevling/**" ]

env:
  CR_NAMESPACE: ${{ secrets.CR_NAMESPACE }}
  CR_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
    - uses: actions/checkout@v3

    - name: Docker login
      run: docker login ghcr.io -u $CR_NAMESPACE -p $CR_TOKEN

    - name: Docker buildx setup
      run: docker buildx create --use --bootstrap

    - name: Docker build and push
      run: docker buildx build . --push --file Dockerfile --tag ghcr.io/$CR_NAMESPACE/tevling:$GITHUB_SHA --tag ghcr.io/$CR_NAMESPACE/tevling:latest --platform linux/arm64,linux/arm,linux/amd64
